[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install -r shop_project/requirements.txt",
    "cd shop_project && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd shop_project && gunicorn shop_project.wsgi:application --bind 0.0.0.0:$PORT"

